### ISSUE TITLE
Problem with translation

### ISSUE THREAD

**Issue by muhajirdev** [emmgfx/material-for-coders#10]
I dont know is this is a bug or no. is there anyway to change this "Continuar leyendo →" word into " Continue Reading"?, My wordpress uses English (US) language.
![Uploading Screenshot from 2015-12-20 22:25:27.png…]()

Nice Project by the way :+1:  :smiley:

**Comment by emmgfx** [comment]
Hi Muhammad.

At the moment the theme is not multilanguage. I assume that the this can come in a few versions... but i don't know when.

I leave this issue here for remember me that someone is interested, and keep it visible to anyone that wants to participate by translating it.

Thanks for the interest. Keep subscribed to this issue. I let you know when any related changes are ready.

**Comment by muhajirdev** [comment]
can i participate to translate this theme?
i can speak indonesian language too btw :)

**Comment by emmgfx** [comment]
If this button is the only issue that you have, we can change it for the default wordpress text, that is well translated.

One question, what version do you have? downloaded through Wordpress or by GitHub?

**Comment by muhajirdev** [comment]
by Github

**Comment by emmgfx** [comment]
Okay. You can update the theme with the Read more button translated.

**Comment by emmgfx** [comment]
@muhajirframe can you check if with the last update you have all the strings in your language?

**Comment by muhajirdev** [comment]
yes there is, 
the word " Volver a la portada" in 404
 "categorias" in the front page, (when opened on mobile)
and "Buscar" on the search placeholder ( when openen on mobile)

**Comment by LennyObez** [comment]
Dear emmgfx,

I make my Github account for your theme ;) As I use it for my WordPress blog, I would like to translate EN (english) -> FR (french).

Thank you in advance,

**Comment by emmgfx** [comment]
@G3notYp3 let mee investigate how the WordPress translation system works and prepare the spanish and english versions. After this you can prepare de french version, of course.

Greetings.

**Comment by LennyObez** [comment]
Thank you for your answer,

Actually, Spanish's version works well and some stuffs is translated in English (in the English's version) like buttons, ... Some stuff like the comments section isn't translated.

Have a nice day !

**Comment by emmgfx** [comment]
@G3notYp3 can you give me the correct fr_FR translations?

**Comment by LennyObez** [comment]
Button: [EN] Read more... -> [FR] Lire plus...
Comment's section: [SP] Puedes dejar el primero : ) -> [FR] Soyez le premier à commenter :)
I don't know if there are more unstranslated text !

**Comment by emmgfx** [comment]
You can update the `languages/fr.po` file with the free [Poedit](http://poedit.net/) software, or simply open it and check the untranslated strings to give me they in a comment.

Thanks :+1:

**Comment by emmgfx** [comment]
Okay. Translations completed and published in Github and in WordPress.

Waiting for review in WP directory: https://themes.trac.wordpress.org/ticket/30685, this process ussualy takes one or two days.

Please, consider leaving some rating on the WordPress Theme Directory: https://wordpress.org/themes/material-for-coders/

Thanks for the translations, @G3notYp3

**Comment by LennyObez** [comment]
Actually, english is working (better than before) but no french at all :/

**Comment by emmgfx** [comment]
Please, in your WP, go to `wp-content/themes/material-for-coders/languages` and try to rename the `fr.*` files to `fr_FR.*`.

If it corrects the issue, you can use the french language now until I can apply it on the next release, that override your changes.

Thanks for the feedback :)

**Comment by emmgfx** [comment]
@G3notYp3 did you tried this?

**Comment by LennyObez** [comment]
My issue is solved by your way ;)

**Comment by LennyObez** [comment]
When I open the hamburger menu, it said categorias; when I search something in the search's bar, it said resultados para; when there is a back button, it said volver a la portada.

Could you add them in the traduction list ?

Closed #10https://github.com/emmgfx/material-for-coders/issues/10.

##

**Comment by emmgfx** [comment]
Of course.

Can you give the french translations for this terms? In english they be something like:

Categorias - Categories
Resultados para - Results for

By the way, I found another bug. The Categories button shouldn't be shown if you don't use the blog menu (I recommend you use it)

**Comment by LennyObez** [comment]
en_EN Categories - fr_FR Catégories
en_EN Results for - fr_FR Résultats pour
sp_SP Volver a la portada - en_EN ?

**Comment by emmgfx** [comment]
@G3notYp3 Volver a la portada == Return home

**Comment by LennyObez** [comment]
en_EN Return home - fr_FR Retourner à l'accueil

**Comment by emmgfx** [comment]
Please, if found another issue, including translation related, open a new issue in order to don't make this too long.
