### ISSUE TITLE
Feature Request : Related Post

### ISSUE THREAD

**Issue by muhajirdev** [emmgfx/material-for-coders#12]
Hi..
i want to request a feature if you dont mind, a related post feature. like the one i saw here https://demo.proteusthemes.com/readable/2014/05/05/maximum-readability/

Thank you :)

**Comment by emmgfx** [comment]
I think that you can use a plugin for this. No?

**Comment by emmgfx** [comment]
You can use [Yet Another Related Posts Plugin](https://es.wordpress.org/plugins/yet-another-related-posts-plugin/) to get this feature, this isn't a theme related issue.
