### ISSUE TITLE
About Author Box

### ISSUE THREAD

**Issue by muhajirdev** [emmgfx/material-for-coders#15]
Hi :smile: 
is there any way to create "about author" box below the post?

**Comment by emmgfx** [comment]
No at the moment.

Maybe in a future but the template isn't made with multi-author in mind, so, if this box exists, must be optional.

I leave the issue opened, but there are no plans to do this in the next weeks.

**Comment by muhajirdev** [comment]
okay :)😇

2015-12-29 14:30 GMT+07:00 Josep Viciana notifications@github.com:

**Comment by emmgfx** [comment]
@muhajirframe option enabled in 1.5.3, check it ;)
