### ISSUE TITLE
Feature request: support infinite scroll from jetpack

### ISSUE THREAD

**Issue by LennyObez** [emmgfx/material-for-coders#17]
Dear emmgfx,

Could you support infinite scrolling from jetpack's extension ?

Thank you in advance,

**Comment by emmgfx** [comment]
Hi Lenny.

Maybe in the future, I can investigate how the jetpack extension works and try to implement on the theme.

**Comment by LennyObez** [comment]
Thank you for your answer,

Your theme is awesome ! Actually, Jetpack extension was made by WordPress team and it's one of the most popular extension ! Supporting this extension is a great + for your theme !

**Comment by emmgfx** [comment]
Hi @G3notYp3, I'm seeing the jetpack documentation and tested a few things. It works well, but, are you sure that this is a good behaviour? I'm thinking on the footer, that turns, in practice, invisible or never accesible.

In what number of post per "scroll" are you thinking? The default is seven, but I think that is really excessive... maybe 2?

**Comment by emmgfx** [comment]
Available since 1.5 :+1:
