### ISSUE TITLE
Issue with the hamburger menu

### ISSUE THREAD

**Issue by LennyObez** [emmgfx/material-for-coders#18]
Dear emmgfx,

There is a problem while you're on smartphone, if you click on it, there is a hover/active state on it but it stays in this state for long.

Could you fix this issue ?

Thank you in advance,

**Comment by LennyObez** [comment]
This is happening on multiple device (Nexus 5 2013, Galaxy S6 Edge and IPhone 5, about the hamburger menu) but my friend with a Galaxy S6 Edge on Firefox can't scroll at all (second issue).

**Comment by emmgfx** [comment]
Uhm... I don't understand... can you give me screenshots of the issues?

2016-02-19 10:36 GMT+01:00 Lenny Obez notifications@github.com:

> This is happening on multiple device (Nexus 5 2013, Galaxy S6 Edge and
> IPhone 5, about the hamburger menu) but my friend with a Galaxy S6 Edge on
> Firefox can't scroll at all (second issue).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/emmgfx/material-for-coders/issues/18#issuecomment-186137004
> .

## 

Josep Viciana,
josep@viciana.me

**Comment by LennyObez** [comment]
![screenshot_20160219-141736](https://cloud.githubusercontent.com/assets/13552115/13176587/a79b4690-d713-11e5-9c44-04ba250ace9d.png)
As you can see, hitting the hamburger menu (on the top-left of the screen) and it will always have the round around the icon ! Active state stays active. It shouldn't. Hitting again the hamburger menu but nothing happend. Round should disappear !

About the Firefox issue, I can't make a screenshot to show you the problem. You can't scroll at all. If you scroll down to see what is under, nothing happend. The page won't move !

**Comment by emmgfx** [comment]
@G3notYp3 try to check it now with the latest update to 1.4.7.1

**Comment by LennyObez** [comment]
I'll wait that WordPress update it, force update won't work right now !

**Comment by emmgfx** [comment]
@G3notYp3 You use the WordPress or the GitHub version? If you are using the WordPress version the update can be quite late. And if you are using the GitHub version (with the portfolio, etc) the update is not automatic, you need to press the button.

Some info about this: http://www.emm-gfx.net/2015/12/wordpress-theme-material-for-coders/

**Comment by LennyObez** [comment]
Actually using the WordPress version, I'll have to wait then !

**Comment by emmgfx** [comment]
Okay, I try to solve other issues before the launch. I notice you through this issue.

**Comment by emmgfx** [comment]
Remember to let me know if the issue is solved : )

**Comment by LennyObez** [comment]
You'll smile :D 

Before, the round around the icon stays gray after hitting it. Now, it stays in a lighter grey (we can say it's near white).

**Comment by emmgfx** [comment]
Uhm... with what browser?

**Comment by LennyObez** [comment]
Chrome for Android AND Firefox for Android

---

De : Josep Viciana notifications@github.com
Envoyé : jeudi 25 février 2016 18:15
À : emmgfx/material-for-coders
Cc : Lenny Obez
Objet : Re: [material-for-coders] Issue with the hamburger menu (#18)

Uhm... with what browser?

##
