### ISSUE TITLE
Issue with quotes

### ISSUE THREAD

**Issue by LennyObez** [emmgfx/material-for-coders#19]
Hello emmgfx,

Your theme is still amazing :) and I'm still using version 1.4.4.3 and I don't know if this
![sans-titre-2](https://cloud.githubusercontent.com/assets/13552115/13215483/e3152eb8-d955-11e5-83de-306b55dd3285.png)
is fixed in the version 1.8 but is it normal there is always a blank space in quote ? No way to fix this manually with the text's editor :(

Have a nice day !

**Comment by emmgfx** [comment]
Current version is 1.4.9, and this bug wasn't notified until now.

Is a very simple css correction, the next update should come with this correction, :+1:

**Comment by emmgfx** [comment]
@VasiliStolz quieres arreglarlo tu?
