### ISSUE TITLE
Menu button don't work

### ISSUE THREAD

**Issue by emmgfx** [emmgfx/material-for-coders#22]
Because jQuery is not loaded.

Check this:
- http://womensrenewal.org
- http://stackoverflow.com/a/22239396/1378408
- https://developer.wordpress.org/reference/functions/wp_enqueue_script/

**Comment by openhouse** [comment]
I was able to fix this by making the following changes

```
// functions.php
add_action( 'wp_enqueue_scripts', 'loadMaterial' );
function loadMaterial() {
    wp_enqueue_script( 'js.js', get_template_directory_uri().'/assets/js/js.js', array('jquery') );
}
```

```
// footer.php
<!--
<script src="<?PHP echo get_template_directory_uri(); ?>/assets/js/js.js"></script>
-->
```

**Comment by emmgfx** [comment]
Great @openhouse , do you want to do the pull request in order to merge this change?

Thank you : )
