### ISSUE TITLE
Bootstrap not working

### ISSUE THREAD

**Issue by dartiss** [emmgfx/material-for-coders#24]
I've attempted to use the Bootstrap shortcodes plugin that you recommend but I find that some of the functionality isn't working - tabbing and message boxes, for instance. In the case of the latter, the dismissal button doesn't work. I found that by re-activating the Bootstrap includes for that plugin caused it to start working again. I also tried some other Bootstrap plugins and found the same thing - when I allowed the plugin to use the Bootstrap code included with this theme, then some of the functions didn't work.

I tried deactivating all other plugins to ensure nothing else was causing a clash but I experienced the same issues.

Is there a solution to this?

**Comment by emmgfx** [comment]
The theme comes only with the CSS of Bootstrap, not includes the Javascript because doesn't use it.

Theorically, if you want to use te javascript components like the dismiss button or the tabs, you only need to enable the plugin Javascript, not the CSS, because it is already integrated in the theme.

**Comment by emmgfx** [comment]
Let me do a test....

**Comment by emmgfx** [comment]
Check this:
http://www.emm-gfx.net/testing-bootstrap-and-material-for-coders/

With this plugin settings:
![captura de pantalla 2016-06-15 10 01 06](https://cloud.githubusercontent.com/assets/1131393/16072255/37734ccc-32e0-11e6-80c7-7093048d89da.png)

**Comment by dartiss** [comment]
Thanks, yes, that worked. I'd actually tried testing that earlier and it didn't seemed to have worked, which was odd. But, yes, thanks. It may be worth updating any instructions to highlight this :smile:
