### ISSUE TITLE
Easy way to modify CSS

### ISSUE THREAD

**Issue by dartiss** [emmgfx/material-for-coders#25]
Does the theme support a custom CSS file? Only modifying the rather large and minimised theme CSS files would be tricky.

In particular, I'm wishing to change the link colours as they don't show.

**Comment by emmgfx** [comment]
Don't edit the theme files. Your changes will be lost in every update.

You can use a lot of plugins to add custom css, but I can't recommend you one because I never used it.

Check this: https://wordpress.org/plugins/search.php?q=custom+css

**Comment by dartiss** [comment]
No, wasn't going to edit the theme. But some allow you to create a file, say custom.css, which will be automatically integrated with the theme's CSS - I just wanted to make sure an equivalent wasn't available before going down the plugin route :)
