### ISSUE TITLE
Alternative text for plural

### ISSUE THREAD

**Issue by LennyObez** [emmgfx/material-for-coders#26]
Hey there,

Can we have a different text when it's plural ?

Thank you.

**Comment by emmgfx** [comment]
Hi @LennyObez .

Where are the plural? Can I see it in your web?

Greetins.

**Comment by LennyObez** [comment]
Pages.

One page.
Unknown number of page(s).
Many pages.

But everytime, it said: "Pages" (in plural)

**Comment by emmgfx** [comment]
In the widget of your sidebar?

This is a wp widget, you can change the title in the widget settings. 

![captura de pantalla 2016-10-04 09 01 51](https://cloud.githubusercontent.com/assets/1131393/19065029/6e8f178a-8a11-11e6-98ce-1230ac6a28dc.png)
