### ISSUE TITLE
Question about the Read More button

### ISSUE THREAD

**Issue by fartbagxp** [emmgfx/material-for-coders#33]
Hi, I'm trying to create a single page blog entry with the theme, and I wasn't sure how to modify it to get it to how I want it to look.

I want a single page blog entry per page, with comments on the bottom and no `Read More` flag.

I read up on this [page](https://codex.wordpress.org/Customizing_the_Read_More) that teaches you how to customize the read more button, but I just want everything to show up on a single page.

Any help is appreciated. Thanks!

**Comment by emmgfx** [comment]
Hi @fartbagxp . I don't get the question.

By default, pages aren't available on the posts loop, so the read more button shouldn't be shown.

Please:

 - Check that your page is a page, not a post.
 - Do you have a public url to view the unwanted Read more button?

**Comment by fartbagxp** [comment]
Ah! That makes sense.

So I am creating posts, and I was wondering how I can use up one page per post without the read more button.

Here's the link: www.fartbagxp.com

Thanks!
