### ISSUE TITLE
Settings not showing in WP4.8

### ISSUE THREAD

**Issue by cefewow** [emmgfx/material-for-coders#36]
this stuff not showing in settings menu:

    register_setting( 'm4c-settings', 'footer-phrase' );
    register_setting( 'm4c-settings', 'color-scheme' );
    register_setting( 'm4c-settings', 'sidebar-active' );
    register_setting( 'm4c-settings', 'procastinate-fonts' );
    register_setting( 'm4c-settings', 'hide-sidebar-xs-window' );
    register_setting( 'm4c-settings', 'show-featured-index' );
    register_setting( 'm4c-settings', 'show-featured-single' );
    register_setting( 'm4c-settings', 'show-featured-single' );
    register_setting( 'm4c-settings', 'show-author-box' );
    register_setting( 'm4c-settings', 'show-excerpt-in-lists' );
    register_setting( 'm4c-settings', 'logo-attachment' );
    register_setting( 'm4c-settings', 'blacked-footer' );

**Comment by emmgfx** [comment]
I'm using 4.8 and I don't have any problems with the settings. Have you checked Appearance / Material for Coders?

**Comment by emmgfx** [comment]
@cefewow did you read the last message?
