### ISSUE TITLE
Javascript for responsive embeds

### ISSUE THREAD

**Issue by emmgfx** [emmgfx/material-for-coders#8]
Visible error:
- http://vasili.es/el-casting-mas-bestia/ (small screens)

Implement this feature:
http://getbootstrap.com/components/#responsive-embed
- Find iframes and objects
- Add `.embed-responsive-item`class to the iframe.
- Wrap it with a `div` with `embed-responsive`and  `embed-responsive-16by9` classes.

/cc @VasiliStolz, :kissing_heart:

**Comment by VasiliStolz** [comment]
thx bro, done :bowtie:
